### ISSUE TITLE
Unable to access FASTA files

### ISSUE THREAD

**Issue by nrminor** [CDCgov/usa-sars-cov-2-nextstrain-sets#2]
Hello,

I'm looking to download the locally weighted FASTA files for Wisconsin, but I've received error 403s or XML errors at every attempt at downloading them. I am able to download the metadata with wget or just by pasting the URLs into my browser, but I've had no such luck with the FASTAs. I also tried setting up the AWS command line interface to download the FASTAs, but receive error 403 with that as well. Granted, I'm new to the aws cli, so it's possible if not likely that this is user error.

Any advice on accessing those FASTAs would be much appreciated!

**Comment by jacaravas** [comment]
@mrminor
It looks like the reference sequence we were using for Nextalign was moved or deleted and the aligned fasta files were not being generated.  The error is corrected for now and I will look into adding some way to catch this in the future.  Please let me know if you have any more issues.

Thank you,
Jason

**Comment by nrminor** [comment]
Many thanks Jason!
