### ISSUE TITLE
FASTA dataset links are broken

### ISSUE THREAD

**Issue by Andrew0Hill** [CDCgov/usa-sars-cov-2-nextstrain-sets#3]
The links to the FASTA files for each state in the `doc_files/files.md` file seem to be broken (or at least the first few I tried were).

You can replicate by trying to access ` https://s3.us-east-1.amazonaws.com/io-pe1-prod-ncezid-oamd-nextstrain/Alabama/Alabama-full-metadata.tsv.xz` which should work correctly, but the corresponding FASTA link `https://s3.us-east-1.amazonaws.com/io-pe1-prod-ncezid-oamd-nextstrain/Alabama/Alabama-full-aligned.fasta.xz` returns an XML "No such key" error for me.

Are these datasets no longer available, or is there some authentication step I am missing in order to be able to download these datasets?

Thanks,
Andrew

**Comment by Andrew0Hill** [comment]
Just realized that this is a duplicate of #2, my apologies.

**Comment by jacaravas** [comment]
> Just realized that this is a duplicate of #2, my apologies.

You were definitely right to post.  I didn't realize this had broken again.  I'll get a fix in ASAP.

**Comment by jacaravas** [comment]
@Andrew0Hill
It was a problem on my end with the data file generation.  I have repaired it and they should all be there now.

**Comment by Andrew0Hill** [comment]
Thanks for fixing this so quickly, much appreciated!
